---
title: "Assignments MAT 4010"
author: "Alan Arnholt"
date: 'Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  html_document:
    css: asu.css
    highlight: textmate
    theme: cosmo
---

**Jan 11:**

* Sign-up for free accounts on [GitHub](https://github.com) and [Rpubs](https://rpubs.com).

* When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **first_name_last_name** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinquishing characteristic in your username.  Please use the same **username** for your account on Rpubs. 

* Once you have a GitHub account, send an email to arnholtat@appstate.edu with a Subject line of **MAT4010 - GitHub Username**, and tell me in the body of your email your first name, last name, and your GitHub username.  I will then manually add you as a team member to the repository in the STAT-ATA-ASU organization that has your name (**Last_name-First_name**).  This repository will be where you store all of your work for this course.  I will also change your repository to a private repository.
 
Watch the following Videos:

* [Phillip Guo's Unix-like command line tutorials (Four tutorials about 10 minutes each)](http://www.pgbovine.net/command-line-tutorial.htm)
* [Phillip Guo's Basic Git and Github tutorials (Three tutorials about 10 minutes each)](http://www.pgbovine.net/git-tutorial.htm)
* [Clone a GitHub Repo with RStudio (Video)](https://www.youtube.com/watch?v=YxZ8J2rqhEM) (5:05)

* Become familiar with the Appstate [RStudio server](https://mathr.math.appstate.edu/). You will use your Appstate user name and password to log in to the server.  You must be registered in the class to access the server.

* Follow the directions from [Jenny Bryan's STAT 545](https://stat545-ubc.github.io/git00_index.html) to [Introduce yourself to Git](https://stat545-ubc.github.io/git04_introduce-self-to-git.html), [Make sure you can communicate with GitHub](https://stat545-ubc.github.io/git05_github-connection.html), [Test drive RStudio and GitHub](https://stat545-ubc.github.io/git07_git-github-rstudio.html), and [Cache your GitHub credentials](https://stat545-ubc.github.io/git06_credential-caching.html).

* Watch this [video](https://www.youtube.com/watch?v=ZFaWxxzouCY&list=PLjTlxb-wKvXNSDfcKPFH2gzHGyjpeCZmJ&index=3) which provides some background on asking questions.  This stackoverflow thread details how to create a [minimal R reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/5963610#5963610). Please read [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html) by Eric Raymond and Rick Moen and heed their advice.

* Read pages 1-37 (Chapters one and two) of _Hands-On Programming with R_.  Create an `Rscripts` folder inside your private repository and store all code in the `Rscripts`  folder for `Project 1`.


**~~Jan 18:~~ No Class**

**Jan 25:**

* Go over cloning as needed
* Writing R functions
* Create an R package - polish documentation during the week
* Read chapters three and four in _Hands-On Programming with R_
* Read chapters one through four of _R Packages_

**Feb 1:**

* Go over RMarkdown documents for chapters [1-2](../RMarkdown/Chapters1and2.html) and [3-4](../RMarkdown/Chapters3and4.html)
* Go over [Package Building](../RMarkdown/PackageBuilding.html)
* Add `shuffle` to your personal package
* Try out each others packages (`devtools::install_github()`) 
* Discuss chapters one through four of _R Packages_
* Read chapters five and six in _Hands-On Programming with R_
* Read chapters five and six of _R Packages_


**Feb 8:**

* Read and summarize chapters five and six of _Hands-On Programming with R_ in an Rmarkdown document.
* Read chapters five and six of _R Packages_

**Feb 15:**

* Discuss chapters [five and six](../RMarkdown/Chapters5and6.html) of _Hands-On Programming with R_
* Discuss chapters five and six of _R Packages_
* Read and summarize chapter [seven](../RMarkdown/Chapter7.html) of _Hands-On Programming with R_ in an Rmarkdown document.
* Read chapter 7 (_Testing_) of _R Packages_
* [Unit Testing Slides](http://www.is.uni-freiburg.de/ressourcen/algorithm-design-and-software-engineering-oeffentlicher-zugriff/11_softwaretesting.pdf)

**Feb 22:**

* Discuss chapters six and seven of _Hands-On Programming with R_
* Put all chapter summaries into one single rmarkdown document.  
* Discuss Unit Testing


**Feb 29:**

* [Documenting S3 Classes, Generics, and Methods](../RMarkdown/OOP.html)
* Make sure Travis-CI is passing
* Work on Group packages - (Individual assignments to follow)
* Push individual notes from chapters 1-7 (one document) to your private repositories before leaving on Spring Break.  

**~~Mar 7 - Mar 11~~ No Class - Spring Break**

**Mar 14:**

* SHA for individual notes
* Go over adding data to packages - see [abbreviated notes](../RMarkdown/PackageBuilding.html) or [R Packages](http://r-pkgs.had.co.nz/data.html) for more detail.
* Work on Group packages

**Mar 21:**

* [Creating data frames from contingency tables](../RMarkdown/CTtoDF.html)
* Work on Group packages
* [Tidy Data Article](https://www.jstatsoft.org/article/view/v059i10)

**~~Mar 28:~~ No Class**

**Apr 4:**

* Discuss and walk through making pull requests. [This is a work in progress](../RMarkdown/BranchesPullRequests.html)
* Read Chapter 13 of [R Packages](http://r-pkgs.had.co.nz/git.html)
* [Using pull requests](https://help.github.com/articles/using-pull-requests/)
* Work on group packages
* Discuss [bookdown](https://github.com/rstudio/bookdown) package.  For `bookdown` documentation see [https://bookdown.org/yihui/bookdown/](https://bookdown.org/yihui/bookdown/).  To install the development version of `bookdown` type the code below at the `R` prompt.

```{r, engine = "bash", eval = FALSE}
devtools::install_github('rstudio/bookdown')
```

**Apr 11:**

**Apr 18:**

**Apr 25:**

**May 2:**

***

#[Home Page](http://stat-ata-asu.github.io/MAT4010Spring2016/) - [Syllabus](http://stat-ata-asu.github.io/MAT4010Spring2016/Syllabus/MAT4010SyllabusSpring2016.html) - [Piazza](https://piazza.com/class/ij30uq82d4p2di)
